[synthea_omop_test]
git-tree-sha1 = "aa21d1ed91986366aa81811d58e75014e76bc102"

    [[synthea_omop_test.download]]
    sha256 = "0753a22279e5a2729af91ee9fa849dae20c503f7c229b9769a6f40d0bc2bc63b"
    url = "https://github.com/AshlinHarris/OmopTestData/raw/refs/heads/main/out/synthea_omop_test.db.tar.gz"
